export interface Cafe {
  id: string;          // UUID generated by DB
  name: string;        // Required
  description: string; // Required
  location: string;    // Required
  logo?: Buffer | string | null; // Optional
  employees?: number;  // Calculated field for GET /cafes
}